//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_03_tilausdb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tilaus_maaria_arkipaivissa
    {
        public long Rivinro { get; set; }
        public string viikkopaiva { get; set; }
        public Nullable<int> number_of_orders { get; set; }
        //public int number_of_orders { get; set; }
    }
}
