//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_03_tilausdb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class top10_tuote_income
    {
        public int Rownumber { get; set; }
        public string product_name { get; set; }
        public Nullable<decimal> income_from_product { get; set; }
    }
}
